* util/texi2dvi (fatal): Rename as... (error): this. If the exit status is 0, don't exit. (run): New. Use it where appropriate. (run_dvipdf): New. Use it.

diff --git a/util/texi2dvi b/util/texi2dvi
--- a/util/texi2dvi
+++ b/util/texi2dvi
@@ -1,6 +1,6 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.84 2006/06/19 09:35:01 akim Exp $
+# $Id: texi2dvi,v 1.85 2006/06/21 08:18:09 akim Exp $
 #
 # Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001,
 # 2002, 2003, 2004, 2005, 2006 Free Software Foundation, Inc.
@@ -35,7 +35,7 @@ unset RUNNING_KSH
 set -e
 
 # This string is expanded by rcs automatically when this file is checked out.
-rcs_revision='$Revision: 1.84 $'
+rcs_revision='$Revision: 1.85 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="texi2dvi (GNU Texinfo 4.8) $rcs_version
@@ -251,7 +251,7 @@ absolute ()
       if test -d "$rel"; then
         (cd "$rel" 2>/dev/null && echo `pwd`/`basename "$1"`);
       else
-        fatal 1 "not a directory: $rel"
+        error 1 "not a directory: $rel"
       fi
       ;;
   esac
@@ -295,6 +295,8 @@ report ()
   done
 }
 
+# verbose WORD1 WORD2
+# -------------------
 # Report some verbose information.
 verbose ()
 {
@@ -303,15 +305,28 @@ verbose ()
   fi
 }
 
-# fatal EXIT_STATUS LINE1 LINE2...
-# --------------------------------
-# Report an error and exit with failure.
-fatal ()
+# run COMMAND-LINE
+# ----------------
+# Run the COMMAND-LINE verbosely, and catching errors as failures.
+run ()
 {
-  s=$1
+  verbose "Running $@"
+  "$@" 2>&5 1>&2 ||
+     error 1 "$1 failed"
+}
+
+
+# error EXIT_STATUS LINE1 LINE2...
+# --------------------------------
+# Report an error and exit with failure if EXIT_STATUS is non null.
+error ()
+{
+  local s=$1
   shift
   report "$@"
-  exit $s
+  if test "$s" != 0; then
+    exit $s
+  fi
 }
 
 # ensure_dir DIR1 DIR2...
@@ -323,7 +338,7 @@ ensure_dir ()
   do
     test -d "$dir" \
       || mkdir "$dir" \
-      || fatal 1 "cannot create directory: $dir"
+      || error 1 "cannot create directory: $dir"
   done
 }
 
@@ -409,7 +424,7 @@ out_lang_tex ()
     dvi | ps | dvipdf ) echo dvi;;
     pdf ) echo $out_lang;;
     html | info | text ) echo $out_lang;;
-    *)    fatal "$0: invalid out_lang: $1";;
+    *)    error "$0: invalid out_lang: $1";;
   esac
 }
 
@@ -422,7 +437,7 @@ out_lang_ext ()
   case $out_lang in
     dvipdf ) echo pdf;;
     dvi | html | info | pdf | ps | text ) echo $out_lang;;
-    *)    fatal "$0: invalid out_lang: $1";;
+    *)    error "$0: invalid out_lang: $1";;
   esac
 }
 
@@ -505,7 +520,7 @@ move_to_dest ()
     *:*)    dest=$(output_base_name "$1");;
   esac
   if test ! -f "$1"; then
-    fatal 1 "no such file or directory: $1"
+    error 1 "no such file or directory: $1"
   fi
   if test -n "$dest"; then
     verbose "Copying $1 to $dest"
@@ -708,7 +723,7 @@ run_tex ()
         esac;;
     texinfo:pdf) tex=$PDFTEX;;
 
-    *) fatal 1 "$0: $out_lang not supported for $in_lang";;
+    *) error 1 "$0: $out_lang not supported for $in_lang";;
   esac
 
   # Beware of aux files in subdirectories that require the
@@ -783,7 +798,7 @@ run_tex ()
       dvi | pdf ) move_to_dest "$in_noext.$out_lang";;
     esac
   else
-    fatal 1 "$tex exited with bad status, quitting."
+    error 1 "$tex exited with bad status, quitting."
   fi
 }
 
@@ -820,9 +835,7 @@ run_bibtex ()
   then
     for f in $(generated_files_get "$in_noext" bibaux_file_p)
     do
-      verbose "Running $bibtex $f ..."
-      $bibtex "$f" >&5 ||
-        fatal 1 "$bibtex exited with bad status, quitting."
+      run $bibtex "$f"
     done
   fi
 }
@@ -841,9 +854,7 @@ run_index ()
   esac
   index_files=`generated_files_get $in_noext index_file_p`
   if test -n "$texindex" && test -n "$index_files"; then
-    verbose "Running $texindex $index_files ..."
-    $texindex $index_files 2>&5 1>&2 ||
-       fatal 1 "$texindex exited with bad status, quitting."
+    run $texindex $index_files
   fi
 }
 
@@ -867,6 +878,29 @@ run_thumbpdf ()
   fi
 }
 
+
+# run_dvipdf FILE.dvi
+# -------------------
+# Convert FILE.dvi to FILE.pdf.
+run_dvipdf ()
+{
+  # Find which dvi->pdf program is available.
+  if test -z "$dvipdf"; then
+    for i in "$DVIPDF" dvipdfmx dvipdfm dvipdf dvi2pdf dvitopdf;
+    do
+      if findprog $i; then
+        dvipdf=$i
+      fi
+    done
+  fi
+  # These tools have varying interfaces, some 'input output', others
+  # 'input -o output'.  They all seem to accept 'input' only,
+  # outputting using the expected file name.
+  run $dvipdf "$1"
+  if test ! -f $(echo "$1" | sed -e 's/\.dvi$/.pdf/'); then
+    error 1 "$0: cannot find output file"
+  fi
+}
 
 # run_tex_suite ()
 # ----------------
@@ -900,7 +934,7 @@ run_tex_suite ()
   # dvipdf or ps).
   case $out_lang in
     dvipdf)
-      dvipdf "$in_noext.$(out_lang_tex)" "$in_noext.$(out_lang_ext)"
+      run_dvipdf "$in_noext.$(out_lang_tex)"
       move_to_dest "$in_noext.$(out_lang_ext)"
       ;;
     ps)
@@ -982,7 +1016,7 @@ run_makeinfo ()
       if test $? != 0; then
         cat $version_test_dir/txiversion.out
         cat $version_test_dir/txiversion.err >&2
-        fatal 1 "texinfo.tex appears to be broken, quitting."
+        error 1 "texinfo.tex appears to be broken, quitting."
       fi
       eval `sed -n 's/^.*\[\(.*\)version \(....\)-\(..\)-\(..\).*$/txiformat=\1 txiversion="\2\3\4"/p' $version_test_dir/txiversion.out`
       verbose "texinfo.tex preloaded as \`$txiformat', version is \`$txiversion' ..."
@@ -1123,7 +1157,7 @@ run_hevea ()
   case $1 in
     html) ;;
     text|info) run_hevea="$run_hevea -$1";;
-    *) fatal "run_hevea: invalid argument: $1";;
+    *) error "run_hevea: invalid argument: $1";;
   esac
 
   # Compiling to the tmp directory enables to preserve a previous
@@ -1136,7 +1170,7 @@ run_hevea ()
 
   verbose "running $run_hevea"
   if eval "$run_hevea" >&5; then :; else
-    fatal 1 "$hevea exited with bad status, quitting."
+    error 1 "$hevea exited with bad status, quitting."
   fi
 }
 
@@ -1158,7 +1192,7 @@ run_core_conversion ()
     latex:html|latex:text|latex:info)
 	run_hevea $out_lang;;
     *)
-	fatal "invalid input/output combination: $in_lang/$out_lang";;
+	error "invalid input/output combination: $in_lang/$out_lang";;
   esac
 
   cd_orig
@@ -1321,7 +1355,7 @@ while test x"$1" != x"$arg_sep"; do
       done
       break;;
     -*)
-      fatal 1 "Unknown or ambiguous option \`$1'." \
+      error 1 "Unknown or ambiguous option \`$1'." \
               "Try \`--help' for more information."
       ;;
     *) set dummy ${1+"$@"} "$1"; shift;;
@@ -1337,18 +1371,18 @@ case $build_mode in
   local) clean=false; tidy=false;;
   tidy)  clean=false; tidy=true;;
   clean) clean=true;  tidy=true;;
-      *) fatal 1 "invalid build mode: $build_mode";;
+      *) error 1 "invalid build mode: $build_mode";;
 esac
 
 # Interpret remaining command line args as filenames.
 case $# in
  0)
-  fatal 2 "Missing file arguments." "Try \`--help' for more information."
+  error 2 "Missing file arguments." "Try \`--help' for more information."
   ;;
  1) ;;
  *)
   if test -n "$oname"; then
-    fatal 2 "Can't use option \`--output' with more than one argument."
+    error 2 "Can't use option \`--output' with more than one argument."
   fi
   ;;
 esac
@@ -1463,7 +1497,7 @@ input_file_name_decode ()
   # prompt (assuming they're attending the terminal), this script won't
   # be able to find the right xref files and so forth.
   test  -r "$command_line_filename" ||
-    fatal 1 "cannot read $command_line_filename, skipping."
+    error 1 "cannot read $command_line_filename, skipping."
 
   # Get the name of the current directory.
   in_dir=`func_dirname "$command_line_filename"`
