from report by Simon Josefsson.

diff --git a/util/texi2dvi b/util/texi2dvi
--- a/util/texi2dvi
+++ b/util/texi2dvi
@@ -1,6 +1,6 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.64 2005/10/05 23:34:19 karl Exp $
+# $Id: texi2dvi,v 1.65 2005/10/24 00:33:43 karl Exp $
 #
 # Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001,
 # 2002, 2003, 2004, 2005 Free Software Foundation, Inc.
@@ -32,7 +32,7 @@ test -f /bin/ksh && test -z "$RUNNING_KSH" \
 unset RUNNING_KSH
 
 # This string is expanded by rcs automatically when this file is checked out.
-rcs_revision='$Revision: 1.64 $'
+rcs_revision='$Revision: 1.65 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="texi2dvi (GNU Texinfo 4.8) $rcs_version
@@ -745,9 +745,10 @@ run_makeinfo ()
 insert_commands ()
 {
   local textra_cmd
-  case language in
+  case $language in
     latex)   textra_cmd=1i;;
     texinfo) textra_cmd='/^@setfilename/a';;
+    *)       echo "$0: internal error, unknown language: $language" >&2;
   esac
 
   if test -n "$textra"; then
