makeinfo

diff --git a/util/texi2dvi b/util/texi2dvi
--- a/util/texi2dvi
+++ b/util/texi2dvi
@@ -1,6 +1,6 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or LaTeX) sources.
-# $Id: texi2dvi,v 1.56 2005/06/24 13:01:37 karl Exp $
+# $Id: texi2dvi,v 1.57 2005/06/24 15:25:41 karl Exp $
 #
 # Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001,
 # 2002, 2003, 2004, 2005 Free Software Foundation, Inc.
@@ -32,7 +32,7 @@ test -f /bin/ksh && test -z "$RUNNING_KSH" \
 unset RUNNING_KSH
 
 # This string is expanded by rcs automatically when this file is checked out.
-rcs_revision='$Revision: 1.56 $'
+rcs_revision='$Revision: 1.57 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="texi2dvi (GNU Texinfo 4.8) $rcs_version
@@ -529,26 +529,66 @@ uncomment_iftex='s/^@c texi2dvi//'
 # main info output, the user asked to run TeX, not makeinfo.
 run_makeinfo ()
 {
-  if test -n "$makeinfo"; then
-    # filename_src: the file with macros expanded.
-    # Use the same basename to generate the same aux file names.
-    work_src=$workdir/src
-    ensure_dir "$work_src"
-    filename_src=$work_src/$filename_noext.$ext
-
-    verbose "Macro-expanding $command_line_filename to $filename_src ..."
-    sed "$comment_iftex" "$command_line_filename" \
-      | $makeinfo --footnote-style=end -I "$filename_dir" $miincludes \
-        -o /dev/null --macro-expand=- \
-      | sed "$uncomment_iftex" >"$filename_src"
-    # Continue only if everything succeeded.
-    if test $? -ne 0 \
-       || test ! -r "$filename_src"; then
-      verbose "Expansion failed, ignored...";
+  case $language in
+  texinfo)
+    # Unless required by the user, makeinfo expansion is wanted only
+    # if texinfo.tex is too old.
+    if test "$expand" = t; then
+      makeinfo=${MAKEINFO:-makeinfo}
     else
-      filename_input=$filename_src
+      # Check if texinfo.tex performs macro expansion by looking for
+      # its version.  The version is a date of the form YEAR-MO-DA.
+      # We don't need to use [0-9] to match the digits since anyway
+      # the comparison with $txiprereq, a number, will fail with non
+      # digits.
+      # Run in a temporary directory to avoid leaving files.
+      version_test_dir=$t2ddir/version_test
+      ensure_dir $version_test_dir
+      (
+         cd $version_test_dir
+         echo '\input texinfo.tex @bye' >txiversion.tex
+         # Be sure that if tex wants to fail, it is not interactive:
+         # close stdin.
+         tex txiversion.tex </dev/null >txiversion.out 2>txiversion.err
+      )
+      if test $? != 0; then
+        cat $version_test_dir/txiversion.out
+        cat $version_test_dir/txiversion.err >&2
+        fatal 1 "texinfo.tex appears to be broken, quitting."
+      fi
+      eval `sed -n 's/^.*\[\(.*\)version \(....\)-\(..\)-\(..\).*$/txiformat=\1 txiversion="\2\3\4"/p' $version_test_dir/txiversion.out`
+      verbose "texinfo.tex preloaded as \`$txiformat', version is \`$txiversion' ..."
+      if test "$txiprereq" -le "$txiversion" >&6 2>&1; then
+        makeinfo=
+      else
+        makeinfo=${MAKEINFO:-makeinfo}
+      fi
+      # As long as we had to run TeX, offer the user this convenience:
+      test "$txiformat" = Texinfo && escape=@
     fi
-  fi
+
+    if test -n "$makeinfo"; then
+      # filename_src: the file with macros expanded.
+      # Use the same basename to generate the same aux file names.
+      work_src=$workdir/src
+      ensure_dir "$work_src"
+      filename_src=$work_src/$filename_noext.$ext
+
+      verbose "Macro-expanding $command_line_filename to $filename_src ..."
+      sed "$comment_iftex" "$command_line_filename" \
+        | $makeinfo --footnote-style=end -I "$filename_dir" $miincludes \
+          -o /dev/null --macro-expand=- \
+        | sed "$uncomment_iftex" >"$filename_src"
+      # Continue only if everything succeeded.
+      if test $? -ne 0 \
+         || test ! -r "$filename_src"; then
+        verbose "Expansion failed, ignored...";
+      else
+        filename_input=$filename_src
+      fi
+    fi
+    ;;
+  esac
 }
 
 # insert_commands ()
@@ -865,7 +905,6 @@ for command_line_filename in ${1+"$@"}; do
       # Assume a LaTeX file.  LaTeX needs bibtex and uses latex for
       # compilation.  No makeinfo.
       language=latex
-      makeinfo= # no point in running makeinfo on latex source.
       textra_cmd=1i
       ;;
 
@@ -873,41 +912,6 @@ for command_line_filename in ${1+"$@"}; do
       # Assume a Texinfo file.
       language=texinfo
       textra_cmd='/^@setfilename/a'
-      # Unless required by the user, makeinfo expansion is wanted only
-      # if texinfo.tex is too old.
-      if test "$expand" = t; then
-        makeinfo=${MAKEINFO:-makeinfo}
-      else
-        # Check if texinfo.tex performs macro expansion by looking for
-        # its version.  The version is a date of the form YEAR-MO-DA.
-        # We don't need to use [0-9] to match the digits since anyway
-        # the comparison with $txiprereq, a number, will fail with non
-        # digits.
-        # Run in a temporary directory to avoid leaving files.
-	version_test_dir=$t2ddir/version_test
-	ensure_dir $version_test_dir
-	(
-           cd $version_test_dir
-	   echo '\input texinfo.tex @bye' >txiversion.tex
-	   # Be sure that if tex wants to fail, it is not interactive:
-	   # close stdin.
-           $tex txiversion.tex </dev/null >txiversion.out 2>txiversion.err
-	)
-	if test $? != 0; then
-	  cat $version_test_dir/txiversion.out
-	  cat $version_test_dir/txiversion.err >&2
-	  fatal 1 "texinfo.tex appears to be broken, quitting."
-        fi
-	eval `sed -n 's/^.*\[\(.*\)version \(....\)-\(..\)-\(..\).*$/txiformat=\1 txiversion="\2\3\4"/p' $version_test_dir/txiversion.out`
-        verbose "texinfo.tex preloaded as \`$txiformat', version is \`$txiversion' ..."
-        if test "$txiprereq" -le "$txiversion" >&6 2>&1; then
-          makeinfo=
-        else
-          makeinfo=${MAKEINFO:-makeinfo}
-        fi
-        # As long as we had to run TeX, offer the user this convenience:
-        test "$txiformat" = Texinfo && escape=@
-      fi
       ;;
   esac
 
