-v when debugging, no binop continuations

diff --git a/util/texi2dvi b/util/texi2dvi
--- a/util/texi2dvi
+++ b/util/texi2dvi
@@ -1,10 +1,10 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.168 2012/01/01 17:09:10 karl Exp $
+# $Id: texi2dvi,v 1.169 2012/01/07 17:16:18 karl Exp $
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001, 2002,
-# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012 Free
-# Software Foundation, Inc.
+# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012
+# Free Software Foundation, Inc.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -34,7 +34,7 @@ unset RUNNING_KSH
 set -e
 
 # This string is expanded automatically when this file is checked out.
-rcs_revision='$Revision: 1.168 $'
+rcs_revision='$Revision: 1.169 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 
@@ -190,8 +190,8 @@ absolute ()
       local rel
       rel=$orig_pwd/`func_dirname "$1"`
       if test -d "$rel"; then
-        (cd "$rel" 2>/dev/null &&
-         local n
+        (cd "$rel" 2>/dev/null \
+         && local n
          n=`pwd`/`basename "$1"`"$slashes"
          echo "$n")
       else
@@ -252,8 +252,8 @@ findprog ()
     # design decisions, so there is little chance to make them consistent.)
     # Thusly, it seems to be difficult to make use of these enhancements.
     #
-    if  { test -f "$dir/$1"     && test -x "$dir/$1"; } ||
-        { test -f "$dir/$1.exe" && test -x "$dir/$1.exe"; }; then
+    if   { test -f "$dir/$1"     && test -x "$dir/$1"; } \
+      || { test -f "$dir/$1.exe" && test -x "$dir/$1.exe"; }; then
       return 0
     fi
   done
@@ -278,8 +278,8 @@ report ()
 run ()
 {
   verbose "Running $@"
-  "$@" 2>&5 1>&2 ||
-     error 1 "$1 failed"
+  "$@" 2>&5 1>&2 \
+  || error 1 "$1 failed"
 }
 
 
@@ -692,8 +692,8 @@ move_to_dest ()
 
   for file
   do
-    test -f "$file" ||
-      error 1 "no such file or directory: $file"
+    test -f "$file" \
+    || error 1 "no such file or directory: $file"
     case $tidy:$oname in
       true:)  destdir=$orig_pwd
               destfile=$destdir/$file;;
@@ -1114,8 +1114,8 @@ run_index ()
 {
   local index_files
   index_files=`generated_files_get $in_noext index_file_p`
-  test -n "$index_files" ||
-    return 0
+  test -n "$index_files" \
+  || return 0
 
   : ${MAKEINDEX:=makeindex}
   : ${TEXINDEX:=texindex}
@@ -1811,14 +1811,15 @@ fi
 
 
 # Enable tracing, and auxiliary tools output.
-#
-# Should be used where you'd typically use /dev/null to throw output
-# away.  But sometimes it is convenient to see that output (e.g., from
-# a grep) to aid debugging.  Especially debugging at distance, via the
-# user.
+# 
+# This fd should be used where you'd typically use /dev/null to throw
+# output away.  But sometimes it is convenient to see that output (e.g.,
+# from a grep) to aid debugging.  Especially debugging at distance, via
+# the user.
+# 
 if $debug; then
   exec 6>&1
-  set -x
+  set -vx
 else
   exec 6>/dev/null
 fi
@@ -1866,8 +1867,8 @@ input_file_name_decode ()
   # though the user may be able to reenter a valid filename at the tex
   # prompt (assuming they're attending the terminal), this script won't
   # be able to find the right xref files and so forth.
-  test -r "$command_line_filename" ||
-    error 1 "cannot read $command_line_filename, skipping."
+  test -r "$command_line_filename" \
+  || error 1 "cannot read $command_line_filename, skipping."
 
   # Get the name of the current directory.
   in_dir=`func_dirname "$command_line_filename"`
