texi2dvi: simplify the handling of --no-line-error. * bin/texi2dvi (no_line_error): Remove, rather use line_error=false. (run_tex): Adjust. By the way, don't call tex --help if !$line_error.

diff --git a/util/texi2dvi b/util/texi2dvi
--- a/util/texi2dvi
+++ b/util/texi2dvi
@@ -1,6 +1,6 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.143 2009/04/15 14:35:00 akim Exp $
+# $Id: texi2dvi,v 1.144 2009/04/15 14:40:31 akim Exp $
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001, 2002, 2003,
 # 2004, 2005, 2006, 2007, 2008, 2009 Free Software Foundation, Inc.
@@ -33,7 +33,7 @@ unset RUNNING_KSH
 set -e
 
 # This string is expanded automatically when this file is checked out.
-rcs_revision='$Revision: 1.143 $'
+rcs_revision='$Revision: 1.144 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 
@@ -51,7 +51,6 @@ escape="\\"
 expand=         # t for expansion via makeinfo
 includes=
 line_error=true # Pass --file-line-error to TeX.
-no_line_error=false  # absolutely do not pass --file-line-error to TeX
 oname=          # --output
 out_lang=dvi
 quiet=false     # by default let the tools' message be displayed
@@ -925,18 +924,18 @@ run_tex ()
   local cmd="$tex"
 
   # If possible, make TeX report error locations in GNU format.
-  if test "${tex_help:+set}" != set; then
-    # Go to a temporary directory to try --help, since old versions that
-    # don't accept --help will generate a texput.log.
-    tex_help_dir=$t2ddir/tex_help
-    ensure_dir "$tex_help_dir"
-    tex_help=`cd "$tex_help_dir" >&6 && $tex --help </dev/null 2>&1 || true`
-  fi
-  if $no_line_error; then :; else
+  if $line_error; then
+    if test "${tex_help:+set}" != set; then
+      # Go to a temporary directory to try --help, since old versions that
+      # don't accept --help will generate a texput.log.
+      tex_help_dir=$t2ddir/tex_help
+      ensure_dir "$tex_help_dir"
+      tex_help=`cd "$tex_help_dir" >&6 && $tex --help </dev/null 2>&1 || true`
+    fi
     # The mk program and perhaps others want to parse TeX's
     # original error messages.
-    case $line_error:$tex_help in
-      true:*file-line-error*) cmd="$cmd --file-line-error";;
+    case $tex_help in
+      *file-line-error*) cmd="$cmd --file-line-error";;
     esac
   fi
 
@@ -1570,7 +1569,7 @@ while test x"$1" != x"$arg_sep"; do
     -I)   shift; list_concat_dirs includes "$1";;
     -l | --lang | --language) shift; set_language=$1;;
     --mostly-clean) action=mostly-clean;;
-    --no-line-error) no_line_error=true;;
+    --no-line-error) line_error=false;;
     -o | --out  | --output)
       shift
       # Make it absolute, just in case we also have --clean, or whatever.
